name: 'Pause Community Contributions'

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  pause:
    name: 'Pause Community Contributions'
    runs-on: ubuntu-latest
    if: github.event.actor.login != 'dependabot' && github.event.actor.login != 'exercism-bot' && github.event.actor.login != 'github-actions[bot]'
    steps:
      - name: Is Organization Member
        id: is-organization-member
        uses: JamesSingleton/is-organization-member@1.0.0
        with:
          organization: exercism
          username: ${{ github.event.actor.login }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Close Issue
        if: steps.is-organization-member.outputs.result == false
        uses: peter-evans/close-issue@v2.2.0
        with:
          issue-number: ${{ github.event.issue.number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment: "Hello. Thanks for opening an issue/PR on Exercism. We are currently in a phase of our journey where we have paused community contributions to allow us to take a breather and redesign our community model. You can learn more in [this blog post](...).\n\n**As such, all issues and PRs in this repository are being automatically closed.**\n\nThat doesn’t mean we’re not interested in your ideas though, and if you’re stuck on something we still want to help. The best place to discuss things is with our community on [the forum](https://forum.exercism.org), so please feel free to copy this into a new topic there.\n\n---\n\n_Note: If you’ve had this issue/PR pre-approved on the forum, please link back to this issue/PR on the forum and a maintainer or @jonathandmiddleton will reopen it._"
